# Generated by Django 4.1.2 on 2022-10-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Familia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiares',
            name='edad',
            field=models.IntegerField(null=True),
        ),
    ]
