# Generated by Django 4.1.2 on 2022-10-12 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Familia', '0002_familiares_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiares',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='familiares',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
