# Generated by Django 4.1.2 on 2022-10-17 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Familia', '0003_familiares_fecha_nacimiento_alter_familiares_edad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiares',
            name='fecha_nacimiento',
        ),
    ]
